'use strict';
const N=NextAction,$=id=>document.getElementById(id),API='https://api.todoist.com/api/v1/',TOKEN='https://api.todoist.com/oauth/access_token',PENDING='next-action.oauth.pending.v1';
const STATES={todo:'To do',progress:'In progress',waiting:'Waiting',done:'Done'};
let token='',refreshToken='',clientId='',accountId='',tasks=[],projects=[],done=[],reviews={},busy=false,demo=false,project='',view='list',base=null,initialDue='',lastSync=0,cooldown=0,writeUncertain=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const url=()=>{const u=new URL(location.href);u.search='';u.hash='';return u;};
function storageKey(){return 'next-action.v1.'+accountId;}
function readPrefs(){try{const x=JSON.parse(localStorage.getItem(storageKey()))||{};reviews=x.reviews&&typeof x.reviews==='object'?x.reviews:{};view=x.view==='board'?'board':'list';}catch{reviews={};view='list';}}
function persist(){if(!accountId||demo)return;try{localStorage.setItem(storageKey(),JSON.stringify({reviews,view}));}catch{say('Browser storage is unavailable. Review dates will last for this session only.',true);}}
function reviewed(id){reviews[id]=Date.now();persist();}
function say(s,error=false){$('notice').textContent=s;$('notice').classList.toggle('error',error);}
function controls(){const connected=!!accountId;for(const id of ['add','refresh'])$(id).disabled=busy||!connected;for(const id of ['connect','logout','demo','forget'])$(id).disabled=busy;$('save').disabled=busy||writeUncertain;$('cancel').disabled=busy;$('logout').hidden=!connected;$('welcome').hidden=connected;$('workspace').hidden=!connected;document.querySelectorAll('.task button,.task select').forEach(n=>n.disabled=busy);}
async function run(fn){if(busy)return;busy=true;controls();$('form-error').textContent='';try{await fn();}catch(e){say(e.message,true);if($('editor').open)$('form-error').textContent=e.message;}finally{busy=false;controls();}}
function disconnect(){token='';refreshToken='';clientId='';accountId='';tasks=[];projects=[];done=[];reviews={};demo=false;base=null;project='';lastSync=0;writeUncertain=false;$('editor').close();$('task-form').reset();$('tasks').replaceChildren();$('projects').replaceChildren();$('account').textContent='Not connected';$('total').textContent='0';$('heading').textContent='Your next action';$('search').value='';$('filter').value='open';try{sessionStorage.removeItem(PENDING);}catch{}controls();}
async function raw(endpoint,options={}){
 let r;try{r=await fetch(endpoint,{...options,credentials:'omit',referrerPolicy:'no-referrer',cache:'no-store',signal:AbortSignal.timeout(25000)});}catch{const write=options.method==='POST'&&endpoint.startsWith(API);if(write)writeUncertain=true;throw Error(write?'The write could not be confirmed. Close the editor, check Todoist, and refresh before making another change.':'Could not reach Todoist. Check your connection and refresh.');}
 if(!r.ok){const e=Error('Todoist returned HTTP '+r.status+'. '+(r.status===429?'Please wait before trying again.':r.status===404?'This task may have been completed or removed. Refresh to check.':'Please try refreshing.'));e.status=r.status;if(r.status===429)cooldown=Date.now()+Math.max(60,Number(r.headers.get('Retry-After'))||0)*1000;if(r.status>=500&&options.method==='POST'&&endpoint.startsWith(API)){writeUncertain=true;e.message+=' The write may have reached Todoist. Check and refresh before another change.';}throw e;}
 if(r.status===204)return null;const text=await r.text();return text?JSON.parse(text):null;
}
async function api(path,method='GET',body){
 if(Date.now()<cooldown)throw Error('Todoist requested a pause. Please try again in about '+Math.ceil((cooldown-Date.now())/1000)+' seconds.');
 if(method!=='GET'&&writeUncertain)throw Error('Refresh and check Todoist before making another change.');
 const request=()=>raw(API+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 try{return await request();}catch(e){if(e.status!==401)throw e;if(!refreshToken){disconnect();throw Error('Your session expired. Connect Todoist again.');}try{const auth=await raw(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:clientId,refresh_token:refreshToken})});token=auth.access_token;refreshToken=auth.refresh_token||refreshToken;if(!token)throw Error();}catch{disconnect();throw Error('Your session expired. Connect Todoist again.');}return request();}
}
function normalize(t){return {...t,id:String(t.id),project_id:String(t.project_id),description:t.description||'',priority:Number(t.priority)||1,labels:t.labels||[]};}
async function sync(quiet=false){
 if(!accountId)return;if(!quiet)say('Refreshing from Todoist…');
 if(!demo){const [nextTasks,nextProjects]=await Promise.all([N.allPages(p=>api(p),'tasks'),N.allPages(p=>api(p),'projects')]);tasks=nextTasks.map(normalize);projects=nextProjects.map(p=>({...p,id:String(p.id)}));done=done.filter(t=>!tasks.some(a=>a.id===t.id));}
 const now=Date.now();for(const t of tasks)if(!Number.isFinite(reviews[t.id]))reviews[t.id]=now;persist();lastSync=now;writeUncertain=false;render();if(!quiet||$('notice').classList.contains('error'))say(demo?'Sample board — changes affect sample data only.':'Up to date. Changes save directly to Todoist.');
}
function projectName(id){return projects.find(p=>p.id===String(id))?.name||'Project';}
function chooseProject(id){project=id;render();}
function renderProjects(){const root=$('projects');root.replaceChildren();$('total').textContent=tasks.length;$('nav-all').classList.toggle('active',!project);for(const p of projects){const b=el('button',undefined,'nav'+(project===p.id?' active':''));b.append(el('span',p.name),el('span',String(tasks.filter(t=>t.project_id===p.id).length)));b.addEventListener("click",()=>chooseProject(p.id));root.append(b);}}
function taskCard(t){
 const card=el('article',undefined,'task');card.dataset.id=t.id;card.draggable=!t._done;card.addEventListener("dragstart",e=>{if(busy){e.preventDefault();return;}e.dataTransfer.setData('text/plain',t.id);e.dataTransfer.effectAllowed='move';});
 const top=el('div',undefined,'task-top'),check=el('button',t._done?'✓':'','check');check.setAttribute('aria-label',(t._done?'Reopen ':'Complete ')+t.content);check.title=t._done?'Reopen task':'Complete task';check.addEventListener("click",()=>run(()=>complete(t)));
 const title=el('h3'),titleButton=el('button',t.content);titleButton.addEventListener("click",()=>openEditor(t));if(t._done){title.textContent=t.content;title.style.textDecoration='line-through';}else title.append(titleButton);top.append(check,title);card.append(top);
 if(t.description)card.append(el('p',t.description));const tags=el('div',undefined,'tags');tags.append(el('span',projectName(t.project_id),'tag'));if(t.priority>1)tags.append(el('span','P'+(5-t.priority),'tag '+(t.priority===4?'urgent':'high')));
 if(t.due){const date=t.due.date?.slice(0,10)||'';tags.append(el('span',(t.due.is_recurring?'↻ ':'')+(date===N.day()?'Today':date||t.due.string||'Scheduled')+(t.due.is_recurring&&t.due.string?' · '+t.due.string:''),'tag '+(date&&date<N.day()&&!t._done?'overdue':'')));}if(t.parent_id)tags.append(el('span','Subtask','tag'));
 const age=N.age(reviews[t.id]);if(age>=7&&!t._done){const badge=el('button','Review · '+age+'d','review'+(age>=14?' old':''));badge.title='Click to confirm this task is still relevant';badge.addEventListener("click",()=>{reviewed(t.id);render();say('Marked still relevant.');});tags.append(badge);}card.append(tags);
 const actions=el('div',undefined,'task-actions');if(!t._done){const select=el('select');select.setAttribute('aria-label','Status for '+t.content);for(const [id,name] of Object.entries(STATES)){const o=el('option',name);o.value=id;select.append(o);}select.value=N.status(t);select.addEventListener("change",()=>{const value=select.value;select.value=N.status(t);run(()=>move(t,value));});actions.append(select);const review=el('button','Still relevant');review.addEventListener("click",()=>{reviewed(t.id);render();say('Marked still relevant.');});actions.append(review);}
 if(!demo){const a=el('a','Todoist ↗');a.href='https://app.todoist.com/app/task/'+encodeURIComponent(t.id);a.target='_blank';a.rel='noopener noreferrer';actions.append(a);}card.append(actions);return card;
}
function render(){
 if(project&&!projects.some(p=>p.id===project))project='';renderProjects();$('heading').textContent=project?projectName(project):'Your next action';
 const scoped=tasks.filter(t=>!project||t.project_id===project);$('open-count').textContent=scoped.length;$('today-count').textContent=N.visible(scoped,{filter:'today'}).length;$('review-count').textContent=N.visible(scoped,{filter:'review',reviews}).length;
 const filter=$('filter').value,settings={project,query:$('search').value.trim(),filter,reviews};let shown=N.sorted(N.visible([...tasks,...done],settings),$('sort').value);
 $('list').setAttribute('aria-pressed',String(view==='list'));$('board').setAttribute('aria-pressed',String(view==='board'));const root=$('tasks');root.replaceChildren();root.className=view;
 if(view==='board'){
  for(const [state,name] of Object.entries(STATES)){
   const column=el('section',undefined,'column');const items=state==='done'?(filter==='open'?N.visible(done,{...settings,filter:'done'}):shown.filter(t=>t._done)):shown.filter(t=>N.status(t)===state);
   const heading=el('div',name+(state==='done'?' · this session':''),'column-title');heading.append(el('span',items.length));column.append(heading);
   column.addEventListener("dragover",e=>{e.preventDefault();column.classList.add('drop');});column.addEventListener("dragleave",()=>column.classList.remove('drop'));column.addEventListener("drop",e=>{e.preventDefault();column.classList.remove('drop');const t=tasks.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(t)run(()=>move(t,state));});
   if(!items.length)column.append(el('p',state==='done'?'Completed tasks appear here.':'Nothing here for now.','column-empty'));items.forEach(t=>column.append(taskCard(t)));root.append(column);
  }
 }else{if(!shown.length)root.append(el('div',filter==='done'?'No tasks completed in this session.':'No tasks match this view.','empty'));shown.forEach(t=>root.append(taskCard(t)));}
 $('results').textContent=shown.length+' '+(filter==='done'?'completed':'matching')+' task'+(shown.length===1?'':'s');$('synced').textContent=demo?'Sample data':lastSync?'Updated '+new Date(lastSync).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})+' · auto-refresh on':'';$('board-hint').hidden=view!=='board';controls();
}
function openEditor(t=null){if(busy||!accountId||t?._done)return;base=t?structuredClone(t):null;$('task-form').reset();$('form-error').textContent='';$('editor-title').textContent=t?'Edit task':'Add a task';$('title').value=t?.content||'';$('notes').value=t?.description||'';$('priority').value=String(t?.priority||1);initialDue=t?.due?.string||t?.due?.datetime||t?.due?.date||'';$('due').value=initialDue;
 const p=$('task-project');p.replaceChildren();for(const item of projects){const o=el('option',item.name);o.value=item.id;p.append(o);}p.value=t?.project_id||project||projects.find(x=>x.is_inbox_project)?.id||projects[0]?.id||'';p.disabled=!!t;
 $('schedule-help').textContent=(t?'Leave the schedule unchanged to preserve its time and recurrence. Project moves are available in Todoist.':'Natural language dates are interpreted in English by Todoist.');$('open-todoist').hidden=!t||demo;if(t)$('open-todoist').href='https://app.todoist.com/app/task/'+encodeURIComponent(t.id);$('editor').showModal();$('title').focus();controls();}
async function save(){
 const input={content:$('title').value.trim(),description:$('notes').value,priority:Number($('priority').value),due:$('due').value,dueChanged:$('due').value!==initialDue};if(!input.content)throw Error('Enter a task title.');let id;
 if(base){const latest=demo?tasks.find(t=>t.id===base.id):normalize(await api('tasks/'+encodeURIComponent(base.id)));if(!latest||latest.checked||latest.is_deleted)throw Error('This task is no longer open. Close the editor and refresh.');const patch=N.editPatch(base,latest,input);
  if(Object.keys(patch).length){if(demo){Object.assign(latest,patch);if(input.dueChanged)latest.due=input.due?{date:input.due,string:input.due}:null;}else await api('tasks/'+encodeURIComponent(base.id),'POST',patch);if(patch.content!==undefined||patch.description!==undefined||patch.due_string!==undefined)reviewed(base.id);}id=base.id;
 }else{const body={content:input.content,description:input.description,priority:input.priority,project_id:$('task-project').value,...(input.due.trim()?{due_string:input.due.trim(),due_lang:'en'}:{})};if(!body.project_id)throw Error('Choose a project.');let created;if(demo){created=normalize({...body,id:crypto.randomUUID(),labels:[],added_at:new Date().toISOString(),due:input.due?{date:input.due,string:input.due}:null});tasks.push(created);}else created=await api('tasks','POST',body);id=String(created.id);reviewed(id);}
 $('editor').close();base=null;await sync(true);say(demo?'Saved to sample data.':'Task saved to Todoist.');
}
async function move(t,state){if(state==='done')return complete(t);if(t._done||N.status(t)===state)return;const latest=demo?t:normalize(await api('tasks/'+encodeURIComponent(t.id)));if(latest.checked||latest.is_deleted)throw Error('This task is no longer open. Refresh to check.');const labels=N.labelsFor(latest,state);if(demo)t.labels=labels;else await api('tasks/'+encodeURIComponent(t.id),'POST',{labels});reviewed(t.id);await sync(true);say('Moved to '+STATES[state]+'.');}
async function complete(t){
 if(t._done){if(demo){tasks.push({...t,_done:false});done=done.filter(x=>x.id!==t.id);}else await api('tasks/'+encodeURIComponent(t.id)+'/reopen','POST');reviewed(t.id);await sync(true);say('Task reopened.');return;}
 const latest=demo?t:normalize(await api('tasks/'+encodeURIComponent(t.id)));if(latest.due?.is_recurring&&JSON.stringify(latest.due)!==JSON.stringify(t.due)){await sync(true);throw Error('This recurring task has a newer schedule in Todoist. The view has been refreshed; check the next occurrence before completing it.');}if(latest.checked||latest.is_deleted){await sync(true);throw Error('This task was already completed or removed. The view has been refreshed.');}
 if(demo){tasks=tasks.filter(x=>x.id!==t.id);if(latest.due?.is_recurring){const next=new Date();next.setDate(next.getDate()+7);tasks.push({...latest,due:{...latest.due,date:N.day(next)}});}}else await api('tasks/'+encodeURIComponent(t.id)+'/close','POST');
 reviewed(t.id);if(!latest.due?.is_recurring)done.unshift({...latest,_done:true});await sync(true);say(latest.due?.is_recurring?'Occurrence completed. Todoist advanced the recurring schedule.':'Completed. Find it in Done this session.');
}
function randomHex(){return Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');}
async function challenge(s){return btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function connect(){if(location.protocol!=='https:')throw Error('Connect Todoist from the HTTPS website. Use the sample board for a local preview.');const page=url(),configURL=new URL('oauth-client.json',page);const config=await raw(configURL.href);if(config.client_id!==configURL.href||config.token_endpoint_auth_method!=='none'||!config.redirect_uris?.includes(page.href))throw Error('The sign-in configuration does not match this page address. Open https://techlifeweb.com/next-action/ and check the uploaded JSON file.');
 const verifier=randomHex(),state=randomHex();sessionStorage.setItem(PENDING,JSON.stringify({verifier,state,clientId:configURL.href,redirect:page.href,created:Date.now()}));const auth=new URL('https://app.todoist.com/oauth/authorize');auth.search=new URLSearchParams({client_id:configURL.href,redirect_uri:page.href,response_type:'code',scope:'data:read_write',state,code_challenge:await challenge(verifier),code_challenge_method:'S256'});say('Opening Todoist…');location.assign(auth.href);}
async function callback(){const params=new URLSearchParams(location.search);if(!params.has('code')&&!params.has('error'))return;history.replaceState(null,'',url().href);let p;try{p=JSON.parse(sessionStorage.getItem(PENDING));}catch{}sessionStorage.removeItem(PENDING);if(!p||p.state!==params.get('state')||!params.get('state')||Date.now()-p.created>900000||p.redirect!==url().href)throw Error('Sign-in could not be verified. Please connect again.');if(params.has('error')||!params.get('code'))throw Error('Todoist sign-in was not completed. You can try again.');say('Connecting your workspace…');const auth=await raw(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:p.clientId,code:params.get('code'),redirect_uri:p.redirect,code_verifier:p.verifier})});if(!auth.access_token)throw Error('No access token was returned. Connect again.');token=auth.access_token;refreshToken=auth.refresh_token||'';clientId=p.clientId;const user=await api('user');const identity=user.id||user.sub;if(!identity){disconnect();throw Error('Todoist did not return an account identifier.');}accountId=String(identity);$('account').textContent=user.full_name||user.name||'Todoist connected';readPrefs();await sync();}
function sample(){disconnect();demo=true;accountId='demo';view='board';projects=[{id:'inbox',name:'Inbox',is_inbox_project:true},{id:'personal',name:'Personal'},{id:'home',name:'Home & life'}];const today=N.day();tasks=[{id:'sample1',content:'Choose one thing to make progress on',description:'A small next step is enough. Take ten minutes and see where it leads.',project_id:'personal',priority:3,due:{date:today,string:'Today'},labels:[]},{id:'sample2',content:'Plan a quiet weekend away',description:'Look at two possible places and pick a date.',project_id:'personal',priority:1,labels:[N.LABELS.progress]},{id:'sample3',content:'Check in about the repair estimate',project_id:'home',priority:2,labels:[N.LABELS.waiting]},{id:'sample4',content:'Sort the photos from our last trip',description:'Start with favorites, not the entire collection.',project_id:'personal',priority:1,labels:[]},{id:'sample5',content:'Pick up groceries',project_id:'home',priority:1,due:{date:today,string:'Today'},labels:[]},{id:'sample6',content:'Make space for the week ahead',description:'Review the calendar and choose a few priorities.',project_id:'inbox',priority:2,labels:[],due:{date:today,string:'Every Friday',is_recurring:true}}].map(t=>normalize({...t,added_at:new Date().toISOString()}));reviews={sample3:Date.now()-16*86400000,sample4:Date.now()-9*86400000};$('account').textContent='Sample workspace';sync();}
$('connect').addEventListener("click",()=>run(connect));$('logout').addEventListener("click",()=>{disconnect();say('Disconnected. Task data and credentials were cleared from this page.');});$('demo').addEventListener("click",sample);$('add').addEventListener("click",()=>openEditor());$('refresh').addEventListener("click",()=>run(()=>sync()));$('nav-all').addEventListener("click",()=>chooseProject(''));$('cancel').addEventListener("click",()=>{$('editor').close();base=null;});$('editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();else base=null;});$('task-form').addEventListener("submit",e=>{e.preventDefault();run(save);});for(const id of ['search','filter','sort'])$(id).addEventListener(id==='search'?'input':'change',render);for(const id of ['list','board'])$(id).addEventListener("click",()=>{view=id;persist();render();});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener("click",()=>{$('filter').value=b.dataset.filter;render();}));$('forget').addEventListener("click",()=>{if(!accountId)return;reviews={};for(const t of tasks)reviews[t.id]=Date.now();persist();render();say('Review clocks restarted for this account in this browser.');});
function autoRefresh(){if(accountId&&!demo&&!busy&&!$('editor').open&&!document.hidden&&navigator.onLine&&Date.now()>=cooldown&&Date.now()-lastSync>30000)run(()=>sync(true));}
setInterval(autoRefresh,60000);document.addEventListener('visibilitychange',autoRefresh);window.addEventListener('focus',autoRefresh);window.addEventListener('online',autoRefresh);window.addEventListener('offline',()=>say('You are offline. Reconnect before changing tasks.',true));
$('date-label').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});controls();if(new URLSearchParams(location.search).get('demo')==='1'&&!new URLSearchParams(location.search).has('code'))sample();else run(callback);
